type Color = (v: string | number) => string;

declare const reset: Color;
declare const bold: Color;
declare const dim: Color;
declare const italic: Color;
declare const underline: Color;
declare const inverse: Color;
declare const hidden: Color;
declare const crossout: Color;
declare const black: Color;
declare const bgBlack: Color;
declare const red: Color;
declare const bgRed: Color;
declare const green: Color;
declare const bgGreen: Color;
declare const yellow: Color;
declare const bgYellow: Color;
declare const blue: Color;
declare const bgBlue: Color;
declare const magenta: Color;
declare const bgMagenta: Color;
declare const cyan: Color;
declare const bgCyan: Color;
declare const white: Color;
declare const bgWhite: Color;
declare const gray: Color;
declare const bgGray: Color;

export { type Color, reset, bold, dim, italic, underline, inverse, hidden, crossout, black, bgBlack, red, bgRed, green, bgGreen, yellow, bgYellow, blue, bgBlue, magenta, bgMagenta, cyan, bgCyan, white, bgWhite, gray, bgGray };
